import { Octokit } from "@octokit/rest";
import type { PRSnapshot } from "@/lib/contracts";
import { getDemoSnapshot } from "@/lib/fixtures";
const LIMIT_FILES = 25; const LIMIT_DIFF_LINES = 2_000; const CONCURRENCY = 8;
export function parsePullRequestUrl(value: string) { const match = value.match(/^https:\/\/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)\/?$/); if (!match) throw new Error("Enter a public GitHub pull-request URL."); return { owner: match[1], repo: match[2], number: Number(match[3]) }; }
function client() { return new Octokit({ auth: process.env.GITHUB_TOKEN }); }
async function fileText(octokit: Octokit, owner: string, repo: string, path: string, ref: string) { const content = await octokit.repos.getContent({ owner, repo, path, ref }); if (Array.isArray(content.data) || content.data.type !== "file") return ""; return Buffer.from(content.data.content, "base64").toString("utf8"); }
async function pooled<T, R>(items: T[], fn: (item: T) => Promise<R>) { const result: R[] = []; let cursor = 0; await Promise.all(Array.from({ length: Math.min(CONCURRENCY, items.length) }, async () => { while (cursor < items.length) { const item = items[cursor++]; result.push(await fn(item)); } })); return result; }
export async function fetchPRContext(prUrl: string) { const { owner, repo, number } = parsePullRequestUrl(prUrl); const octokit = client(); const { data: pr } = await octokit.pulls.get({ owner, repo, pull_number: number }); const agents = await Promise.all(["AGENTS.md", ".github/AGENTS.md"].map(async (path) => { try { return { path, content: await fileText(octokit, owner, repo, path, pr.head.sha) }; } catch { return { path, content: "" }; } })); const found = agents.find((entry) => entry.content); return { owner, repo, number, title: pr.title, agentsMarkdown: found?.content || null, agentsPath: found?.path || null }; }
export async function fetchSnapshot(prUrl: string): Promise<PRSnapshot> { const demo = getDemoSnapshot(prUrl); if (demo) return demo; const { owner, repo, number } = parsePullRequestUrl(prUrl); const octokit = client(); try { const [{ data: pr }, { data: files }, diffResponse] = await Promise.all([octokit.pulls.get({ owner, repo, pull_number: number }), octokit.pulls.listFiles({ owner, repo, pull_number: number, per_page: 100 }), fetch(`https://github.com/${owner}/${repo}/pull/${number}.diff`, { headers: { Accept: "application/vnd.github.v3.diff" } })]); if (files.length > LIMIT_FILES) throw new Error(`PR too large: maximum ${LIMIT_FILES} changed files.`); const unifiedDiff = diffResponse.ok ? await diffResponse.text() : ""; if (unifiedDiff.split(/\r?\n/).length > LIMIT_DIFF_LINES) throw new Error(`PR too large: maximum ${LIMIT_DIFF_LINES} diff lines.`); const changedFiles = await pooled(files, async (file) => ({ path: file.filename, content: file.status === "removed" ? "" : await fileText(octokit, owner, repo, file.filename, pr.head.sha), status: file.status === "added" ? "added" as const : file.status === "removed" ? "removed" as const : "modified" as const })); return { owner, repo, number, title: pr.title, unifiedDiff, changedFiles }; } catch (error) { if (error instanceof Error) throw error; throw new Error("GitHub could not retrieve this pull request."); } }