import { z } from "zod";
import { compileContract, validateProviderContract } from "@/lib/compiler";
import type { CompiledContract, Finding, PRSnapshot } from "@/lib/contracts";

const findingSchema = z.object({ rule: z.string(), filePath: z.string(), line: z.number().int().positive(), violationType: z.string(), action: z.string(), confidence: z.enum(["high", "low"]) });
const responseSchema = z.object({ findings: z.array(findingSchema).max(10) });
const jsonSchema = { type: "object", properties: { findings: { type: "array", items: { type: "object", properties: { rule: { type: "string" }, filePath: { type: "string" }, line: { type: "integer" }, violationType: { type: "string" }, action: { type: "string" }, confidence: { type: "string", enum: ["high", "low"] } }, required: ["rule", "filePath", "line", "violationType", "action", "confidence"] } } }, required: ["findings"] };
type Provider = "nvidia" | "gemini" | "ollama";
const system = "Return only JSON. Check only changed code. Never invent a rule, file, line, or evidence.";
function hunk(snapshot: PRSnapshot, filePath: string, line: number) { const content = snapshot.changedFiles.find((f) => f.path === filePath)?.content.split(/\r?\n/)[line - 1] ?? ""; return snapshot.unifiedDiff.includes(content) ? snapshot.unifiedDiff.slice(0, 1000) : `Pre-existing: ${filePath}:${line}`; }
async function nvidia(messages: unknown, schema: unknown) { const key = process.env.NVIDIA_API_KEY; if (!key) throw new Error("NVIDIA inference is not configured."); const response = await fetch("https://integrate.api.nvidia.com/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.NVIDIA_MODEL || "google/gemma-4-31b-it", temperature: 0, response_format: { type: "json_object" }, messages }), signal: AbortSignal.timeout(45_000) }); if (!response.ok) throw new Error(`NVIDIA inference failed (${response.status}).`); return JSON.parse((await response.json() as { choices?: { message?: { content?: string } }[] }).choices?.[0]?.message?.content || "{}"); }
async function gemini(prompt: string, schema: unknown) { const key = process.env.GEMINI_API_KEY; const model = process.env.GEMINI_MODEL; if (!key || !model) throw new Error("Gemini fallback is not configured."); const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents: [{ role: "user", parts: [{ text: prompt }] }], generationConfig: { responseMimeType: "application/json", responseSchema: schema, temperature: 0 } }), signal: AbortSignal.timeout(30_000) }); if (!response.ok) throw new Error(`Gemini inference failed (${response.status}).`); return JSON.parse((await response.json() as { candidates?: { content?: { parts?: { text?: string }[] } }[] }).candidates?.[0]?.content?.parts?.[0]?.text || "{}"); }
async function ollama(messages: unknown, schema: unknown) { const base = process.env.OLLAMA_BASE_URL; if (!base || process.env.NODE_ENV === "production") throw new Error("Ollama is unavailable."); const response = await fetch(`${base.replace(/\/$/, "")}/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OLLAMA_MODEL || "gemma4-12b-lmstudio", stream: false, format: schema, messages }), signal: AbortSignal.timeout(90_000) }); if (!response.ok) throw new Error(`Ollama inference failed (${response.status}).`); return JSON.parse((await response.json() as { message?: { content?: string } }).message?.content || "{}"); }
async function request(provider: Provider, messages: unknown, schema: unknown, prompt: string) { return provider === "nvidia" ? nvidia(messages, schema) : provider === "gemini" ? gemini(prompt, schema) : ollama(messages, schema); }
async function withProvider<T>(messages: unknown, schema: unknown, prompt: string, parse: (value: unknown, provider: Provider) => T): Promise<{ value: T; provider: Provider }> { const providers: Provider[] = process.env.NODE_ENV === "production" ? ["nvidia", "gemini"] : ["nvidia", "gemini", "ollama"]; let last: unknown; for (const provider of providers) { try { return { value: parse(await request(provider, messages, schema, prompt), provider), provider }; } catch (error) { last = error; } } throw last instanceof Error ? last : new Error("No AI provider is available."); }
export async function compileWithProviders(spec: string) { if (!process.env.NVIDIA_API_KEY && !(process.env.GEMINI_API_KEY && process.env.GEMINI_MODEL)) return compileContract(spec); const messages = [{ role: "system", content: "Compile this contract into JSON with checks and unexpressibleRules. Allowed modes only: restricted-import, restricted-syntax, path-glob, dependency, required-test, judgment." }, { role: "user", content: spec }]; try { const result = await withProvider(messages, { type: "object" }, spec, (value, provider) => validateProviderContract(value, spec, provider)); return result.value; } catch { return compileContract(spec); } }
export async function judgeWithProviders(snapshot: PRSnapshot, contract: CompiledContract): Promise<{ findings: Finding[]; provider: Provider }> { if (!contract.unexpressibleRules.length) return { findings: [], provider: "ollama" }; const context = { rules: contract.unexpressibleRules, changedFiles: snapshot.changedFiles.map((file) => ({ path: file.path, content: file.content.slice(0, 12000) })) }; const messages = [{ role: "system", content: system }, { role: "user", content: JSON.stringify(context) }]; const result = await withProvider(messages, jsonSchema, `${system}\n${JSON.stringify(context)}`, (value) => responseSchema.parse(value)); const findings = result.value.findings.flatMap((entry, index) => { const file = snapshot.changedFiles.find((candidate) => candidate.path === entry.filePath); if (!file || !contract.unexpressibleRules.includes(entry.rule) || entry.line > file.content.split(/\r?\n/).length) return []; return [{ id: `judgment-${index + 1}`, requirementQuote: entry.rule, specLine: 1, filePath: entry.filePath, line: entry.line, diffHunk: hunk(snapshot, entry.filePath, entry.line), violationType: entry.violationType, action: entry.action, source: "llm" as const, confidence: entry.confidence, preExisting: hunk(snapshot, entry.filePath, entry.line).startsWith("Pre-existing") }]; }); return { findings, provider: result.provider }; }